spring:
  mail:
    default-encoding: UTF-8
    host: smtp.yandex.ru
    port: 465
    username: el.grilgo@yandex.by
    password: cmctmbqulklmrlve
    protocol: smtp
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.yandex.ru