spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery-food
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.yandex.ru
    port: 465
    username: el.grilgo@yandex.by
    password: cmctmbqulklmrlve
    protocol: smtp
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.yandex.ru
client:
  recipe:
    url: http://localhost:8889/api/recipe