spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery-food
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: el.grilgo@gmail.com
    password: unefmqhkiuiugzso
    protocol: smtp
    properties:
      mail:
        tls:
          enable: true
        smtp:
          auth: true
          starttls.enable: true
          tls.trust: smtp.gmail.com
client:
  recipe:
    url: http://localhost:8889/api/recipe